version: '3'
services:
   etl:
      build: .
      container_name: etl-spark
      depends_on:
         - postgres
      links:
         - postgres
      environment: 
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_HOST: postgres
         POSTGRES_PORT: 5432
         POSTGRES_DB: ETL
      volumes:
         - ./data:/home/data
         - ./main.py:/usr/spark-2.4.1/main.py
         - ./config_manager.py:/usr/spark-2.4.1/config_manager.py
         - ./data_processor.py:/usr/spark-2.4.1/data_processor.py
   postgres:
      build: postgres/docker
      image: postgres
      restart: always
      container_name: postgres
      ports:
         - "5432:5432"
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
         POSTGRES_DB: ETL
   
